theme: jekyll-theme-minimal
title: [Drug-Resistant Infections and Disease Dynamics group handbook]
description: [Welcome to our group's handbook. This is intended to help group members to find the information they need, and to give prospective members an idea about what it is like to work with our group.]

